name = "btr-risk"
compatibility_date = "2024-01-15"

# Required for Pages when using wrangler.toml
pages_build_output_dir = "./dist"

[env.production]
name = "btr-risk"
[env.production.vars]
NODE_VERSION = "20.10.0"
BUN_VERSION = "1.2.16"
NEXT_TELEMETRY_DISABLED = "1"

[env.preview]
name = "btr-risk-preview"
[env.preview.vars]
NODE_VERSION = "20.10.0"
BUN_VERSION = "1.2.16"
NEXT_TELEMETRY_DISABLED = "1"
